// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-876hx9FbbEncUfHrPXclV5sSjxt32g',
    appId: '1:475818153439:android:ab9ec7e1fc3f30580a606a',
    messagingSenderId: '475818153439',
    projectId: 'mind-series',
    databaseURL: 'https://mind-series-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mind-series.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGMmacqpmwy4BWL2gnjs85V7KrdHYGmZk',
    appId: '1:475818153439:ios:342700b1a0886a1c0a606a',
    messagingSenderId: '475818153439',
    projectId: 'mind-series',
    databaseURL: 'https://mind-series-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mind-series.appspot.com',
    androidClientId: '475818153439-mubidtbgh6dc5didh313hot3h6qi3kgk.apps.googleusercontent.com',
    iosClientId: '475818153439-n8bffqa7i539vjvq6v15eq75ffc805ld.apps.googleusercontent.com',
    iosBundleId: 'com.hamda.mindseries',
  );
}
